version: '3'
services:
  sqlserver:
    image: core/sqlserver
    environment:
      - HAB_LICENSE=accept-no-persist
  contosouniversity:
    image: mwrock/contosouniversity
    ports:
      - "80:8099"
    environment:
      - HAB_LICENSE=accept-no-persist
    links:
      - sqlserver
    depends_on:
      - sqlserver
    command: --peer sqlserver --bind database:sqlserver.default --strategy at-once --channel unstable

networks:
  default:
    external:
      name: nat
